[package]
authors = ["Erik Johnston <erikj@matrix.org>"]
name = "matrix-ircd"
version = "0.1.0"

[dependencies]
clap = "2.14.0"
futures = "0.1.1"
httparse = "1.1.2"
lazy_static = "0.2.1"
native-tls = "0.1.1"
netbuf = "0.3.2"
pest = "0.4.0"
quick-error = "1.1.0"
rand = "0.3.14"
serde = "0.9.0"
serde_derive = "0.9.0"
serde_json = "0.9.0"
slog-term = "1.1.0"
tokio-core = "0.1.0"
tokio-dns-unofficial = "0.1.0"
tokio-proto = "0.1.0"
tokio-tls = "0.1.1"
url = "1.2.1"

[dependencies.openssl]
version = "0.9.0"

[dependencies.slog]
version = "1.0.0"

[dependencies.tasked-futures]
git = "https://github.com/erikjohnston/tasked-futures.git"
optional = false

[dependencies.tokio-timer]
git = "https://github.com/tokio-rs/tokio-timer"

[features]
clippy = []
default = []
trace_logging = ["slog/max_level_trace", "slog/release_max_level_warn"]
