[package]
authors = ["Erik Johnston <erikj@matrix.org>"]
name = "matrix-ircd"
version = "0.1.0"

[dependencies]
clap = "2.14.0"
futures = "0.1.1"
httparse = "1.1.2"
itertools = "0.5.6"
lazy_static = "0.2.1"
netbuf = "0.3.2"
pest = "0.4.0"
quick-error = "1.1.0"
rand = "0.3.14"
serde = "0.8.10"
serde_derive = "0.8.10"
serde_json = "0.8.2"
slog-term = "1.1.0"
tokio-core = "0.1.0"
url = "1.2.1"

[dependencies.openssl]
features = ["x509_clone"]
version = "0.8.3"

[dependencies.slog]
version = "1.0.0"

[dependencies.tasked-futures]
git = "https://github.com/erikjohnston/tasked-futures.git"
optional = false

[dependencies.tokio-dns]
branch = "erikj/crates-io-deps"
git = "https://github.com/erikjohnston/tokio-dns"
optional = false

[dependencies.tokio-proto]
git = "https://github.com/tokio-rs/tokio-proto"

[dependencies.tokio-timer]
git = "https://github.com/tokio-rs/tokio-timer"

[dependencies.tokio-tls]
features = ["force-openssl"]
git = "https://github.com/tokio-rs/tokio-tls"

[features]
clippy = []
default = []
trace_logging = ["slog/max_level_trace", "slog/release_max_level_warn"]
